linters-settings:
  misspell:
    locale: US
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: var-naming
        severity: warning
        arguments:
          # Список аббревиатур, которые могут НЕ быть в верхнем регистре
          - - ID
            - UI
            - URL
            - URI
            - API
            - JSON
            - SQL
            - HTTP
            - TLS
            - SSL
            - UUID
            - SMTP
            - IP
            - DNS
          # Список аббревиатур, которые должны быть в верхнем регистре
#          - - VM
      - name: line-length-limit
        severity: warning
        arguments: [ 140 ]
      - name: unexported-return
        severity: warning
      - name: errorf
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: range
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: empty-block
        severity: warning
      - name: superfluous-else
        severity: warning
      - name: confusing-naming
        severity: warning
      - name: get-return
        severity: warning
      - name: deep-exit
        severity: warning
      - name: unused-parameter
        severity: warning
      - name: unreachable-code
        severity: warning
#      - name: flag-parameter
#        severity: warning
      - name: unnecessary-stmt
        disabled: true
      - name: struct-tag
        severity: warning
      - name: constant-logical-expr
        severity: warning
      - name: bool-literal-in-expr
        severity: warning
      - name: atomic
        severity: warning
      - name: string-of-int
        severity: warning
      - name: early-return
        severity: warning
      - name: unconditional-recursion
        severity: warning
      - name: identical-branches
        severity: warning
  govet:
    check-shadowing: true
    # Settings per analyzer.
    enable-all: true
    disable:
      - fieldalignment
  cyclop:
    max-complexity: 15
  gocritic:
    disabled-checks:
      - commentFormatting

linters:
  disable-all: true
  enable:
    - typecheck
    - misspell
    - govet
    - revive
    - ineffassign
    - gosimple
    - unparam
    - unused
    - asciicheck
    - dogsled
    - dupl
    - gosec
    - whitespace
    - cyclop
    - contextcheck
    - bidichk
    - errname
    - nilnil
    - durationcheck
    - unconvert
    - gocritic

service:
  golangci-lint-version: 1.51.1 # use the fixed version to not introduce new linters unexpectedly

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    # TODO(y4m4): Remove once all exported ident. have comments!
    - comment on exported function
    - comment on exported type
    - should have comment
    - use leading k in Go names
    - comment on exported const
run:
  tests: false
  skip-dirs-use-default: true
  timeout: 5m